#include "config/config_project_manager.h"
#include "config/config_project_manager_p.h"
#include "config/modbus_mapping_utils.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QRegularExpression>
#include <QSettings>
#include <QSet>
#include <QStringList>
#include <QTextStream>
#include <QUuid>

#include <type_traits>

namespace configtool {

namespace detail {

SourceInfo makeSourceInfo(const QString &filePath)
{
    QFileInfo info(filePath);

    SourceInfo source;
    source.filePath = info.filePath();
    source.fileName = info.fileName();
    return source;
}

PointSignalType signalTypeForService(ModelServiceType type)
{
    switch (type) {
    case ModelServiceType::Measurement:
        return PointSignalType::Yc;
    case ModelServiceType::Status:
        return PointSignalType::Yx;
    case ModelServiceType::Control:
        return PointSignalType::Ctrl;
    }

    return PointSignalType::Yc;
}

ModelServiceType serviceTypeFromIndex(int index)
{
    switch (index) {
    case 0:
        return ModelServiceType::Measurement;
    case 1:
        return ModelServiceType::Status;
    case 2:
        return ModelServiceType::Control;
    default:
        return ModelServiceType::Measurement;
    }
}

ModelServiceType inferServiceType(const QJsonObject &pointObject)
{
    const QString doType = pointObject.value(QStringLiteral("DOtype")).toString().trimmed();
    const QString doName = pointObject.value(QStringLiteral("DOname")).toString().trimmed();
    const QString dataType = pointObject.value(QStringLiteral("datatype")).toString().trimmed();

    const QString upperDoType = doType.toUpper();
    const QString lowerDoName = doName.toLower();
    const QString lowerDataType = dataType.toLower();

    if (upperDoType.contains(QStringLiteral("CO"))
        || upperDoType.contains(QStringLiteral("SPC"))
        || upperDoType.contains(QStringLiteral("DPC"))
        || lowerDoName.contains(QStringLiteral("ctl"))
        || lowerDoName.contains(QStringLiteral("set"))) {
        return ModelServiceType::Control;
    }

    if (upperDoType.contains(QStringLiteral("SPS"))
        || upperDoType.contains(QStringLiteral("DPS"))
        || upperDoType.contains(QStringLiteral("INS"))
        || lowerDataType == QStringLiteral("bool")
        || lowerDataType == QStringLiteral("boolean")) {
        return ModelServiceType::Status;
    }

    return ModelServiceType::Measurement;
}

PointTemplate parsePointTemplate(const QJsonObject &pointObject,
                                 ModelServiceType serviceType,
                                 const SourceInfo &source)
{
    PointTemplate point;
    point.pointId = QUuid::createUuid().toString(QUuid::WithoutBraces);
    point.category = serviceType;
    point.signalType = signalTypeForService(serviceType);
    point.northVisible = !pointObject.contains(QStringLiteral("northVisible"))
        || pointObject.value(QStringLiteral("northVisible")).toBool(true);
    point.name = pointObject.value(QStringLiteral("DOname")).toString();
    point.description = pointObject.value(QStringLiteral("description")).toString();
    point.ldName = pointObject.value(QStringLiteral("LDname")).toString();
    point.lnType = pointObject.value(QStringLiteral("LNtype")).toString();
    point.lnInst = pointObject.value(QStringLiteral("LNinst")).toString();
    point.doName = pointObject.value(QStringLiteral("DOname")).toString();
    point.doType = pointObject.value(QStringLiteral("DOtype")).toString();
    point.dataType = pointObject.value(QStringLiteral("datatype")).toString();
    point.unit = pointObject.value(QStringLiteral("unit")).toString();
    point.deadZoneType = pointObject.value(QStringLiteral("deadzonetype")).toString();
    point.deadZoneValue = pointObject.value(QStringLiteral("deadzoneval")).toString();
    point.min = pointObject.value(QStringLiteral("min")).toString();
    point.max = pointObject.value(QStringLiteral("max")).toString();
    point.step = pointObject.value(QStringLiteral("step")).toString();
    point.maxLength = pointObject.value(QStringLiteral("maxlength")).toString();
    if (pointObject.value(QStringLiteral("extensions")).isObject()) {
        point.extensions = pointObject.value(QStringLiteral("extensions")).toObject();
    }
    for (const QString &key : {
             QStringLiteral("autoGenerated"),
             QStringLiteral("generatedBy"),
             QStringLiteral("derivedMainDeviceId"),
             QStringLiteral("derivedSourceDeviceId"),
             QStringLiteral("derivedSourceDataRef"),
             QStringLiteral("derivedTargetDeviceId"),
             QStringLiteral("derivedTargetDataRef")
         }) {
        if (pointObject.contains(key)) {
            point.extensions.insert(key, pointObject.value(key));
        }
    }
    point.source = source;

    if (serviceType == ModelServiceType::Control) {
        const QString lowerDataType = point.dataType.toLower();
        point.controlKind = lowerDataType == QStringLiteral("boolean")
            || lowerDataType == QStringLiteral("dbool")
            ? ControlKind::RemoteControl
            : ControlKind::RemoteAdjust;
    }

    return point;
}

bool loadJsonDocument(const QString &filePath,
                      QJsonDocument &document,
                      QString &errorMessage)
{
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        errorMessage = QStringLiteral("无法打开文件");
        return false;
    }

    const QByteArray payload = file.readAll();
    file.close();

    QJsonParseError parseError;
    document = QJsonDocument::fromJson(payload, &parseError);
    if (parseError.error != QJsonParseError::NoError || !document.isObject()) {
        errorMessage = QStringLiteral("JSON 解析失败: %1").arg(parseError.errorString());
        return false;
    }

    return true;
}

QString safeFileSegment(const QString &value,
                       const QString &fallback)
{
    QString result = value.trimmed();
    if (result.isEmpty()) {
        result = fallback.trimmed();
    }

    result.replace(QRegularExpression(QStringLiteral("[\\/:*?\"<>|]+")), QStringLiteral("_"));
    result.replace(QRegularExpression(QStringLiteral("\\s+")), QStringLiteral("_"));
    result.replace(QRegularExpression(QStringLiteral("_+")), QStringLiteral("_"));
    result.remove(QRegularExpression(QStringLiteral("^_+|_+$")));
    return result.isEmpty() ? QStringLiteral("unnamed") : result;
}

QString jsonValueToString(const QJsonValue &value)
{
    if (value.isString()) {
        return value.toString();
    }
    if (value.isDouble()) {
        const double number = value.toDouble();
        const int integer = value.toInt();
        return qFuzzyCompare(number + 1.0, static_cast<double>(integer) + 1.0)
            ? QString::number(integer)
            : QString::number(number);
    }
    if (value.isBool()) {
        return value.toBool() ? QStringLiteral("true") : QStringLiteral("false");
    }
    return QString();
}

int parseModbusLinePart(const QString &line, int sectionIndex)
{
    return line.section(QLatin1Char('_'), sectionIndex, sectionIndex).trimmed().toInt(nullptr, 0);
}

bool isCompleteModbusLine(const QString &line, int expectedParts)
{
    if (line.trimmed().isEmpty()) {
        return false;
    }

    return line.split(QLatin1Char('_'), Qt::KeepEmptyParts).size() >= expectedParts + 1;
}

QJsonObject qSettingsGroupRawExtra(QSettings &settings,
                                   const QSet<QString> &knownKeys)
{
    QJsonObject rawExtra;
    const QStringList keys = settings.allKeys();
    for (const QString &key : keys) {
        if (knownKeys.contains(key)) {
            continue;
        }
        rawExtra.insert(key, settings.value(key).toString());
    }
    return rawExtra;
}

bool modbusBindingMatchesPollGroup(const PointBinding &binding,
                                   const ModbusPollGroup &group)
{
    bool ok = false;
    const uint dataIndex = binding.address.toUInt(&ok, 0);
    return ok && static_cast<int>(dataIndex >> 16) == group.groupNo;
}

bool modbusBindingMatchesSetPoint(const PointBinding &binding,
                                  const ModbusSetPoint &setPoint)
{
    bool ok = false;
    const uint dataIndex = binding.address.toUInt(&ok, 0);
    if (!ok) {
        return false;
    }
    return static_cast<int>(dataIndex >> 16) == setPoint.groupNo
        && static_cast<int>(dataIndex & 0xffff) == setPoint.entryNo;
}

void annotateModbusBinding(PointBinding &binding,
                            const ModbusDeviceConfig &modbus)
{
    bool ok = false;
    const uint dataIndex = binding.address.toUInt(&ok, 0);
    if (!ok) {
        return;
    }

    const int groupNo = static_cast<int>(dataIndex >> 16);
    const int entryNo = static_cast<int>(dataIndex & 0xffff);
    binding.extensions.insert(QStringLiteral("modbusGroupNo"), groupNo);
    binding.extensions.insert(QStringLiteral("modbusEntryNo"), entryNo);

    for (const ModbusSetPoint &setPoint : modbus.setPoints) {
        if (modbusBindingMatchesSetPoint(binding, setPoint)) {
            binding.extensions.insert(QStringLiteral("modbusKind"), modbusPointKindId(setPoint.kind));
            binding.extensions.insert(QStringLiteral("modbusFunctionCode"), setPoint.funCode);
            binding.extensions.insert(QStringLiteral("modbusRegisterAddress"), setPoint.regAddr);
            binding.extensions.insert(QStringLiteral("modbusDataType"), setPoint.dataType);
            binding.extensions.insert(QStringLiteral("modbusScale"), setPoint.scale);
            return;
        }
    }

    for (const ModbusPollGroup &group : modbus.pollGroups) {
        if (modbusBindingMatchesPollGroup(binding, group)) {
            const int entryNo = static_cast<int>(dataIndex & 0xffff);
            const int regStep = group.dataType == QStringLiteral("DWORD")
                || group.dataType == QStringLiteral("DWORD_L")
                || group.dataType == QStringLiteral("FLOAT")
                ? 2
                : (group.dataType == QStringLiteral("FLOAT_L") ? 4 : 1);
            binding.extensions.insert(QStringLiteral("modbusKind"), modbusPointKindId(group.kind));
            binding.extensions.insert(QStringLiteral("modbusFunctionCode"), group.funCode);
            binding.extensions.insert(QStringLiteral("modbusRegisterAddress"), group.startAddr + ((entryNo - 1) * regStep));
            binding.extensions.insert(QStringLiteral("modbusStartAddress"), group.startAddr);
            binding.extensions.insert(QStringLiteral("modbusRegisterCount"), group.regNum);
            binding.extensions.insert(QStringLiteral("modbusDataType"), group.dataType);
            binding.extensions.insert(QStringLiteral("modbusScale"), group.scale);
            return;
        }
    }
}

bool isDeviceForProtocol(const ProtocolDeviceInstance &device,
                         ProtocolType protocol)
{
    if (device.protocol == protocol) {
        return true;
    }
    if (protocol == ProtocolType::Iec104) {
        return device.appType.compare(QStringLiteral("South_104"), Qt::CaseInsensitive) == 0
            || device.appType.compare(QStringLiteral("cepiec104"), Qt::CaseInsensitive) == 0;
    }
    if (protocol == ProtocolType::Dlt645) {
        return device.appType.compare(QStringLiteral("South_645"), Qt::CaseInsensitive) == 0
            || device.appType.compare(QStringLiteral("cepdlt645"), Qt::CaseInsensitive) == 0;
    }
    if (protocol == ProtocolType::Modbus) {
        return device.appType.compare(QStringLiteral("South_Modbus"), Qt::CaseInsensitive) == 0
            || device.appType.compare(QStringLiteral("cepmodbus"), Qt::CaseInsensitive) == 0;
    }
    return false;
}

QList<ProtocolDeviceInstance> devicesForProtocol(const ConfigProject &project,
                                                 ProtocolType protocol)
{
    QList<ProtocolDeviceInstance> devices;
    for (const ProtocolDeviceInstance &device : project.devices) {
        if (isDeviceForProtocol(device, protocol)) {
            devices.append(device);
        }
    }
    return devices;
}

QSet<QString> modelIdsUsedByDevices(const QList<ProtocolDeviceInstance> &devices)
{
    QSet<QString> modelIds;
    for (const ProtocolDeviceInstance &device : devices) {
        if (!device.modelId.trimmed().isEmpty()) {
            modelIds.insert(device.modelId);
        }
    }
    return modelIds;
}

QList<ModelTemplate> modelsForDeviceSet(const ConfigProject &project,
                                        const QSet<QString> &modelIds)
{
    QList<ModelTemplate> models;
    for (const ModelTemplate &model : project.models) {
        if (modelIds.contains(model.modelId)) {
            models.append(model);
        }
    }
    return models;
}

QString modbusKindString(ModbusPointKind kind)
{
    return modbusPointKindId(kind);
}

QString modbusPollKeyPrefix(ModbusPointKind kind)
{
    return kind == ModbusPointKind::Yx ? QStringLiteral("yx") : QStringLiteral("yc");
}

QString modbusSetKeyPrefix(ModbusPointKind kind)
{
    return kind == ModbusPointKind::Yk ? QStringLiteral("yk") : QStringLiteral("yt");
}

QString modbusIniPollLine(const ModbusPollGroup &group)
{
    return QStringLiteral("_%1_%2_%3_%4")
        .arg(group.groupNo)
        .arg(group.funCode)
        .arg(group.startAddr)
        .arg(group.regNum);
}

QString modbusIniSetLine(const ModbusSetPoint &setPoint)
{
    return QStringLiteral("_%1_%2_%3_%4")
        .arg(setPoint.groupNo)
        .arg(setPoint.entryNo)
        .arg(setPoint.funCode)
        .arg(setPoint.regAddr);
}

QString dlt645IniPollLine(const Dlt645PollGroup &group)
{
    return QStringLiteral("poll_%1_%2_%3_%4")
        .arg(group.groupNo)
        .arg(group.funCode, 0, 16)
        .arg(group.pollDi.trimmed().toUpper())
        .arg(group.dataLength);
}

QString dlt645IniSetLine(const Dlt645SetPoint &setPoint)
{
    QString line = QStringLiteral("set_%1_%2_%3_%4")
        .arg(setPoint.groupNo)
        .arg(setPoint.entryNo)
        .arg(setPoint.funCode, 0, 16)
        .arg(setPoint.di.trimmed().toUpper());
    if (setPoint.kind == Dlt645PointKind::Yt) {
        line += QStringLiteral("_%1").arg(setPoint.dataLength);
    }
    return line;
}

QString modelFileNameForExport(const ModelTemplate &model)
{
    return model.modelId.trimmed() + QStringLiteral(".json");
}

QString deviceFileNameForExport(const ProtocolDeviceInstance &device)
{
    const QString stem = !device.deviceId.trimmed().isEmpty()
        ? device.deviceId
        : device.deviceDesc;
    return QStringLiteral("device-%1.json")
        .arg(safeFileSegment(stem, QStringLiteral("device")));
}

QJsonObject serializePoint(const PointTemplate &point)
{
    QJsonObject object;
    object.insert(QStringLiteral("DOname"), point.doName);
    object.insert(QStringLiteral("DOtype"), point.doType);
    object.insert(QStringLiteral("LDname"), point.ldName);
    object.insert(QStringLiteral("LNinst"), point.lnInst);
    object.insert(QStringLiteral("LNtype"), point.lnType);
    object.insert(QStringLiteral("datatype"), point.dataType);
    object.insert(QStringLiteral("deadzonetype"), point.deadZoneType);
    object.insert(QStringLiteral("deadzoneval"), point.deadZoneValue);
    object.insert(QStringLiteral("description"), point.description);
    object.insert(QStringLiteral("max"), point.max);
    object.insert(QStringLiteral("maxlength"), point.maxLength);
    object.insert(QStringLiteral("min"), point.min);
    object.insert(QStringLiteral("step"), point.step);
    object.insert(QStringLiteral("unit"), point.unit);
    if (!point.northVisible) {
        object.insert(QStringLiteral("northVisible"), false);
    }
    if (!point.extensions.isEmpty()) {
        object.insert(QStringLiteral("extensions"), point.extensions);
    }
    return object;
}

QString exportedServiceId(ModelServiceType type)
{
    switch (type) {
    case ModelServiceType::Measurement:
        return QStringLiteral("analog");
    case ModelServiceType::Status:
        return QStringLiteral("discrete");
    case ModelServiceType::Control:
        return QStringLiteral("control");
    }

    return QStringLiteral("analog");
}

QString exportedServiceDescription(ModelServiceType type)
{
    switch (type) {
    case ModelServiceType::Measurement:
        return QStringLiteral("遥测");
    case ModelServiceType::Status:
        return QStringLiteral("遥信");
    case ModelServiceType::Control:
        return QStringLiteral("控制");
    }

    return QStringLiteral("遥测");
}

QJsonObject serializeModel(const ModelTemplate &model, bool northOnly)
{
    QJsonObject profile;
    profile.insert(QStringLiteral("devType"), model.deviceType);
    profile.insert(QStringLiteral("manufacturerDesc"), model.manufacturerDesc);
    profile.insert(QStringLiteral("manufacturerId"), model.manufacturerId);
    profile.insert(QStringLiteral("model"), model.modelId);
    profile.insert(QStringLiteral("modelDesc"), model.displayName);
    profile.insert(QStringLiteral("version"), model.version);

    QJsonArray servicesArray;
    for (ModelServiceType serviceType : {ModelServiceType::Measurement, ModelServiceType::Status, ModelServiceType::Control}) {
        QJsonObject serviceObject;
        QJsonArray pointsArray;
        const ServiceTemplate *service = model.findService(serviceType);
        if (service) {
            for (const PointTemplate &point : service->points) {
                if (northOnly && !point.northVisible) {
                    continue;
                }
                pointsArray.append(serializePoint(point));
            }
        }
        serviceObject.insert(QStringLiteral("DOs"), pointsArray);
        serviceObject.insert(QStringLiteral("description"),
            service && !service->displayName.trimmed().isEmpty()
                ? service->displayName
                : exportedServiceDescription(serviceType));
        serviceObject.insert(QStringLiteral("serviceId"),
            service && !service->serviceId.trimmed().isEmpty()
                ? (service->serviceId == QStringLiteral("measurement")
                    ? exportedServiceId(serviceType)
                    : (service->serviceId == QStringLiteral("status")
                        ? exportedServiceId(serviceType)
                        : service->serviceId))
                : exportedServiceId(serviceType));
        servicesArray.append(serviceObject);
    }

    QJsonObject root;
    root.insert(QStringLiteral("profile"), profile);
    root.insert(QStringLiteral("schema"), model.schema);
    root.insert(QStringLiteral("services"), servicesArray);
    return root;
}

QJsonObject serializeModel(const ModelTemplate &model)
{
    return serializeModel(model, false);
}

QJsonObject serializeNorthModel(const ModelTemplate &model)
{
    return serializeModel(model, true);
}

QString normalizedExportedServiceId(const ServiceTemplate &service)
{
    if (service.serviceId == QStringLiteral("measurement")
        || service.serviceId == QStringLiteral("status")
        || service.serviceId.trimmed().isEmpty()) {
        return exportedServiceId(service.type);
    }

    return service.serviceId;
}

QMap<QString, QSet<QString>> loadNorthModelRefsByService(const QString &filePath,
                                                         ImportReport &report)
{
    QMap<QString, QSet<QString>> refsByService;
    QJsonDocument document;
    QString errorMessage;
    if (!loadJsonDocument(filePath, document, errorMessage)) {
        report.addIssue(ImportIssueSeverity::Warning, filePath,
                        QStringLiteral("无法读取 northmodel，已按模型不可见处理：%1").arg(errorMessage));
        return refsByService;
    }

    const QJsonArray services = document.object().value(QStringLiteral("services")).toArray();
    for (const QJsonValue &serviceValue : services) {
        if (!serviceValue.isObject()) {
            continue;
        }
        const QJsonObject serviceObject = serviceValue.toObject();
        const QString serviceId = serviceObject.value(QStringLiteral("serviceId")).toString();
        if (serviceId.trimmed().isEmpty()) {
            continue;
        }
        const QJsonArray points = serviceObject.value(QStringLiteral("DOs")).toArray();
        for (const QJsonValue &pointValue : points) {
            if (!pointValue.isObject()) {
                continue;
            }
            const QJsonObject pointObject = pointValue.toObject();
            const QString dataRef = pointObject.value(QStringLiteral("LDname")).toString()
                + QLatin1Char('.')
                + pointObject.value(QStringLiteral("LNtype")).toString()
                + QLatin1Char('.')
                + pointObject.value(QStringLiteral("LNinst")).toString()
                + QLatin1Char('.')
                + pointObject.value(QStringLiteral("DOname")).toString();
            if (!dataRef.isEmpty() && dataRef != QStringLiteral("...")) {
                refsByService[serviceId].insert(dataRef);
            }
        }
    }

    return refsByService;
}

void applyNorthModelVisibility(const QString &modelDir,
                               ConfigProject &project,
                               ImportReport &report)
{
    QDir northDir(QDir(modelDir).filePath(QStringLiteral("northmodel")));
    if (!northDir.exists()) {
        return;
    }

    const QString modelDirPath = QDir(modelDir).absolutePath();
    for (ModelTemplate &model : project.models) {
        if (QFileInfo(model.source.filePath).absoluteDir().absolutePath() != modelDirPath) {
            continue;
        }

        const QString northFilePath = northDir.filePath(modelFileNameForExport(model));
        if (!QFileInfo::exists(northFilePath)) {
            model.northVisible = false;
            for (ServiceTemplate &service : model.services) {
                for (PointTemplate &point : service.points) {
                    point.northVisible = false;
                }
            }
            continue;
        }

        model.northVisible = true;
        const QMap<QString, QSet<QString>> refsByService = loadNorthModelRefsByService(northFilePath, report);
        for (ServiceTemplate &service : model.services) {
            const QString serviceId = normalizedExportedServiceId(service);
            const QSet<QString> allowedRefs = refsByService.value(serviceId);
            for (PointTemplate &point : service.points) {
                point.northVisible = allowedRefs.contains(point.dataRef());
            }
        }
    }
}

QHash<QString, QString> buildDataRefDescriptionMap(const ModelTemplate *model)
{
    QHash<QString, QString> descriptions;
    if (!model) {
        return descriptions;
    }

    for (const ServiceTemplate &service : model->services) {
        for (const PointTemplate &point : service.points) {
            descriptions.insert(point.dataRef(), point.description);
        }
    }

    return descriptions;
}

QHash<QString, int> buildModelPointOrderMap(const ModelTemplate *model)
{
    QHash<QString, int> orderMap;
    if (!model) {
        return orderMap;
    }

    int order = 0;
    for (const ServiceTemplate &service : model->services) {
        for (const PointTemplate &point : service.points) {
            orderMap.insert(point.dataRef(), order++);
        }
    }

    return orderMap;
}

QJsonObject serializeBinding(const PointBinding &binding,
                             const QHash<QString, QString> &descriptionMap)
{
    QJsonObject object;
    object.insert(QStringLiteral("dataIndex"), binding.address);
    object.insert(QStringLiteral("dataRef"), binding.dataRef);
    object.insert(QStringLiteral("description"), binding.descriptionOverride.isEmpty()
        ? descriptionMap.value(binding.dataRef)
        : binding.descriptionOverride);
    object.insert(QStringLiteral("retain"), binding.retain);
    if (!binding.selfSignalFlag.isEmpty()) {
        object.insert(QStringLiteral("self_sig_flag"), binding.selfSignalFlag);
    }
    if (!binding.initValue.isEmpty()) {
        object.insert(QStringLiteral("init_value"), binding.initValue);
    }
    return object;
}

QList<PointBinding> bindingsForExport(const ProtocolDeviceInstance &device,
                                      const QHash<QString, int> &orderMap)
{
    QList<QPair<int, PointBinding>> orderedBindings;
    orderedBindings.reserve(device.bindings.size());
    const bool allowEmptyAddress = isDeviceForProtocol(device, ProtocolType::Modbus)
        && device.transport.protocolOptions.value(QStringLiteral("type"))
               .toString().trimmed().compare(QStringLiteral("VIRTUAL"), Qt::CaseInsensitive) == 0;

    for (int index = 0; index < device.bindings.size(); ++index) {
        const PointBinding &binding = device.bindings.at(index);
        if (!binding.enabled
            || (!allowEmptyAddress
                && !isVirtualPointBinding(binding)
                && binding.address.trimmed().isEmpty())) {
            continue;
        }

        const int order = orderMap.contains(binding.dataRef)
            ? orderMap.value(binding.dataRef)
            : (100000 + index);
        orderedBindings.append(qMakePair(order, binding));
    }

    std::sort(orderedBindings.begin(), orderedBindings.end(), [](const auto &left, const auto &right) {
        return left.first < right.first;
    });

    QList<PointBinding> result;
    result.reserve(orderedBindings.size());
    for (const auto &item : orderedBindings) {
        result.append(item.second);
    }
    return result;
}

QJsonObject serializeDevice(const ProtocolDeviceInstance &device,
                            const ModelTemplate *model)
{
    const QHash<QString, QString> descriptionMap = buildDataRefDescriptionMap(model);
    const QHash<QString, int> orderMap = buildModelPointOrderMap(model);
    const QList<PointBinding> exportBindings = bindingsForExport(device, orderMap);

    QJsonArray bindingArray;
    for (const PointBinding &binding : exportBindings) {
        bindingArray.append(serializeBinding(binding, descriptionMap));
    }

    QJsonObject root;
    root.insert(QStringLiteral("DeviceDesc"), device.deviceDesc);
    root.insert(QStringLiteral("DeviceId"), device.deviceId);
    root.insert(QStringLiteral("Model"), device.modelId);
    root.insert(QStringLiteral("addr"), device.transport.stationAddress);
    root.insert(QStringLiteral("ipa"), device.transport.ip);
    if (device.transport.source.rawExtra.contains(QStringLiteral("ipb"))) {
        root.insert(QStringLiteral("ipb"), device.transport.source.rawExtra.value(QStringLiteral("ipb")));
    }
    root.insert(QStringLiteral("meas_points"), bindingArray);
    root.insert(QStringLiteral("port"), device.transport.port);
    return root;
}

QJsonObject serializeModbusBinding(const PointBinding &binding,
                                   const QHash<QString, QString> &descriptionMap)
{
    QJsonObject object;
    object.insert(QStringLiteral("dataIndex"), binding.address);
    object.insert(QStringLiteral("dataRef"), binding.dataRef);
    object.insert(QStringLiteral("description"), binding.descriptionOverride.isEmpty()
        ? descriptionMap.value(binding.dataRef)
        : binding.descriptionOverride);
    object.insert(QStringLiteral("retain"), binding.retain);
    const QJsonValue scaleValue = binding.extensions.value(QStringLiteral("modbusPointScale"));
    if (!scaleValue.isUndefined() && !scaleValue.isNull()) {
        object.insert(QStringLiteral("scale"), scaleValue);
    }
    const bool pocketBit = binding.extensions.value(QStringLiteral("modbusDataType")).toString()
        .compare(QStringLiteral("POCKETBIT"), Qt::CaseInsensitive) == 0;
    if (pocketBit && binding.extensions.contains(QStringLiteral("modbusSourceIndex"))) {
        object.insert(QStringLiteral("sourceIndex"), binding.extensions.value(QStringLiteral("modbusSourceIndex")));
    }
    if (pocketBit && binding.extensions.contains(QStringLiteral("modbusBitIndex"))) {
        object.insert(QStringLiteral("bitIndex"), binding.extensions.value(QStringLiteral("modbusBitIndex")));
    }
    if (!binding.selfSignalFlag.isEmpty()) {
        object.insert(QStringLiteral("self_sig_flag"), binding.selfSignalFlag);
    }
    if (!binding.initValue.isEmpty()) {
        object.insert(QStringLiteral("init_value"), binding.initValue);
    }
    const bool controlPoint = isModbusSetKind(modbusBindingKind(binding));
    if (controlPoint && binding.extensions.contains(QStringLiteral("precontrol_dataIndex"))) {
        object.insert(QStringLiteral("precontrol_dataIndex"), binding.extensions.value(QStringLiteral("precontrol_dataIndex")));
    }
    if (controlPoint && binding.extensions.contains(QStringLiteral("precontrol_val"))) {
        object.insert(QStringLiteral("precontrol_val"), binding.extensions.value(QStringLiteral("precontrol_val")));
    }
    if (binding.extensions.contains(QStringLiteral("linkto"))) {
        object.insert(QStringLiteral("linkto"), binding.extensions.value(QStringLiteral("linkto")));
    }
    if (binding.extensions.contains(QStringLiteral("virdot"))) {
        object.insert(QStringLiteral("virdot"), binding.extensions.value(QStringLiteral("virdot")));
    }
    return object;
}

QJsonObject serializeModbusDevice(const ProtocolDeviceInstance &device,
                                  const ModelTemplate *model)
{
    const QHash<QString, QString> descriptionMap = buildDataRefDescriptionMap(model);
    const QHash<QString, int> orderMap = buildModelPointOrderMap(model);
    const QList<PointBinding> exportBindings = bindingsForExport(device, orderMap);

    QJsonArray bindingArray;
    for (const PointBinding &binding : exportBindings) {
        bindingArray.append(serializeModbusBinding(binding, descriptionMap));
    }

    const QString type = device.transport.protocolOptions.value(QStringLiteral("type")).toString(QStringLiteral("TCP")).trimmed().toUpper();

    QJsonObject root;
    root.insert(QStringLiteral("DeviceId"), device.deviceId);
    root.insert(QStringLiteral("DeviceDesc"), device.deviceDesc);
    root.insert(QStringLiteral("Model"), device.modelId);
    root.insert(QStringLiteral("addr"), device.transport.stationAddress);
    root.insert(QStringLiteral("type"), type);
    if (type == QStringLiteral("RTU")) {
        QJsonObject rtu;
        rtu.insert(QStringLiteral("serialPort"), jsonValueToString(device.transport.serial.value(QStringLiteral("serialPort"))));
        for (const QString &key : {QStringLiteral("baud"), QStringLiteral("dataBits"), QStringLiteral("stopBits")}) {
            bool ok = false;
            const int value = jsonValueToString(device.transport.serial.value(key)).toInt(&ok);
            rtu.insert(key, ok ? QJsonValue(value) : device.transport.serial.value(key));
        }
        rtu.insert(QStringLiteral("parity"), jsonValueToString(device.transport.serial.value(QStringLiteral("parity"))));
        root.insert(QStringLiteral("rtu"), rtu);
    } else if (type == QStringLiteral("TCP")) {
        root.insert(QStringLiteral("ip"), device.transport.ip);
        bool ok = false;
        const int port = device.transport.port.toInt(&ok);
        root.insert(QStringLiteral("port"), ok ? QJsonValue(port) : QJsonValue(device.transport.port));
    }

    const QString debug = device.transport.protocolOptions.value(QStringLiteral("debug")).toString().trimmed();
    if (!debug.isEmpty() && debug.compare(QStringLiteral("off"), Qt::CaseInsensitive) != 0) {
        root.insert(QStringLiteral("debug"), debug);
    }
    bool timeoutOk = false;
    const int responseTimeoutMs = jsonValueToString(
        device.transport.protocolOptions.value(QStringLiteral("responseTimeoutMs"))).toInt(&timeoutOk);
    root.insert(QStringLiteral("responseTimeoutMs"), timeoutOk && responseTimeoutMs > 0
        ? QJsonValue(responseTimeoutMs)
        : QJsonValue(500));
    root.insert(QStringLiteral("meas_points"), bindingArray);
    return root;
}

QJsonObject serializeDlt645Device(const ProtocolDeviceInstance &device,
                                  const ModelTemplate *model)
{
    const QHash<QString, QString> descriptionMap = buildDataRefDescriptionMap(model);
    const QHash<QString, int> orderMap = buildModelPointOrderMap(model);
    const QList<PointBinding> exportBindings = bindingsForExport(device, orderMap);

    QJsonArray bindingArray;
    for (const PointBinding &binding : exportBindings) {
        QJsonObject object = serializeBinding(binding, descriptionMap);
        for (const QString &key : {
                 QStringLiteral("dlt645Kind"),
                 QStringLiteral("dlt645PointDI"),
                 QStringLiteral("dlt645PollDI"),
                 QStringLiteral("dlt645FunctionCode"),
                 QStringLiteral("dlt645DataType"),
                 QStringLiteral("dlt645DataLength"),
                 QStringLiteral("dlt645GroupNo"),
                 QStringLiteral("dlt645EntryNo")
             }) {
            if (binding.extensions.contains(key)) {
                object.insert(key, binding.extensions.value(key));
            }
        }
        if (binding.extensions.contains(QStringLiteral("linkto"))) {
            object.insert(QStringLiteral("linkto"), binding.extensions.value(QStringLiteral("linkto")));
        }
        if (binding.extensions.contains(QStringLiteral("virdot"))) {
            object.insert(QStringLiteral("virdot"), binding.extensions.value(QStringLiteral("virdot")));
        }
        bindingArray.append(object);
    }

    QJsonObject root;
    root.insert(QStringLiteral("DeviceId"), device.deviceId);
    root.insert(QStringLiteral("DeviceDesc"), device.deviceDesc);
    root.insert(QStringLiteral("Model"), device.modelId);
    root.insert(QStringLiteral("addr"), device.transport.stationAddress);

    if (!device.transport.serial.isEmpty()) {
        QJsonObject rtu;
        rtu.insert(QStringLiteral("serialPort"), jsonValueToString(device.transport.serial.value(QStringLiteral("serialPort"))));
        for (const QString &key : {QStringLiteral("baud"), QStringLiteral("dataBits"), QStringLiteral("stopBits")}) {
            bool ok = false;
            const int value = jsonValueToString(device.transport.serial.value(key)).toInt(&ok);
            rtu.insert(key, ok ? QJsonValue(value) : device.transport.serial.value(key));
        }
        rtu.insert(QStringLiteral("parity"), jsonValueToString(device.transport.serial.value(QStringLiteral("parity"))));
        root.insert(QStringLiteral("rtu"), rtu);
    }

    root.insert(QStringLiteral("meas_points"), bindingArray);
    return root;
}

bool writeJsonFile(const QString &filePath,
                   const QJsonObject &object,
                   QString &errorMessage)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        errorMessage = QStringLiteral("无法写入文件");
        return false;
    }

    const QByteArray payload = QJsonDocument(object).toJson(QJsonDocument::Indented);
    if (file.write(payload) < 0) {
        errorMessage = QStringLiteral("写入 JSON 内容失败");
        file.close();
        return false;
    }

    file.close();
    return true;
}

bool removeJsonFilesInDirectory(const QString &dirPath,
                                QString &errorMessage)
{
    QDir dir(dirPath);
    if (!dir.exists()) {
        return true;
    }

    const QFileInfoList files = dir.entryInfoList(
        QStringList() << QStringLiteral("*.json"),
        QDir::Files | QDir::NoDotAndDotDot,
        QDir::Name);
    for (const QFileInfo &file : files) {
        if (!QFile::remove(file.absoluteFilePath())) {
            errorMessage = QStringLiteral("无法删除旧文件: %1").arg(file.absoluteFilePath());
            return false;
        }
    }

    return true;
}

bool writeTextFile(const QString &filePath,
                   const QString &content,
                   QString &errorMessage)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text)) {
        errorMessage = QStringLiteral("无法写入文件");
        return false;
    }

    QTextStream stream(&file);
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
    stream.setEncoding(QStringConverter::Utf8);
#else
    stream.setCodec("UTF-8");
#endif
    stream << content;
    if (stream.status() != QTextStream::Ok) {
        errorMessage = QStringLiteral("写入文本内容失败");
        file.close();
        return false;
    }

    file.close();
    return true;
}

QString buildModbusIniContent(const ConfigProject &project,
                              const QList<ProtocolDeviceInstance> &devices)
{
    QString content;
    QTextStream stream(&content);

    stream << "[Base]\n";
    stream << "frameInterval=" << (project.modbus.frameInterval.trimmed().isEmpty()
        ? QStringLiteral("100")
        : project.modbus.frameInterval.trimmed()) << "\n";
    if (!project.modbus.hwVariant.trimmed().isEmpty()) {
        stream << "hw_variant=" << project.modbus.hwVariant.trimmed() << "\n";
    }
    if (!project.modbus.yxUploadPeriod.trimmed().isEmpty()) {
        stream << "YX_UploadPeriod=" << project.modbus.yxUploadPeriod.trimmed() << "\n";
    }
    if (!project.modbus.ycUploadPeriod.trimmed().isEmpty()) {
        stream << "YC_UploadPeriod=" << project.modbus.ycUploadPeriod.trimmed() << "\n";
    }
    for (const QString &key : project.modbus.rawExtra.keys()) {
        stream << key << "=" << project.modbus.rawExtra.value(key).toString() << "\n";
    }

    for (const ProtocolDeviceInstance &device : devices) {
        QList<ModbusPollGroup> yxPolls;
        QList<ModbusPollGroup> ycPolls;
        QList<ModbusSetPoint> ykSets;
        QList<ModbusSetPoint> ytSets;

        for (const ModbusPollGroup &group : device.modbus.pollGroups) {
            if (group.kind == ModbusPointKind::Yx) {
                yxPolls.append(group);
            } else {
                ycPolls.append(group);
            }
        }
        for (const ModbusSetPoint &setPoint : device.modbus.setPoints) {
            if (setPoint.kind == ModbusPointKind::Yk) {
                ykSets.append(setPoint);
            } else {
                ytSets.append(setPoint);
            }
        }

        auto sortByOrder = [](const auto &left, const auto &right) {
            if (left.order != right.order) {
                return left.order < right.order;
            }
            if (left.groupNo != right.groupNo) {
                return left.groupNo < right.groupNo;
            }
            if constexpr (std::is_same_v<std::decay_t<decltype(left)>, ModbusSetPoint>) {
                return left.entryNo < right.entryNo;
            } else {
                return left.startAddr < right.startAddr;
            }
        };
        std::sort(yxPolls.begin(), yxPolls.end(), sortByOrder);
        std::sort(ycPolls.begin(), ycPolls.end(), sortByOrder);
        std::sort(ykSets.begin(), ykSets.end(), sortByOrder);
        std::sort(ytSets.begin(), ytSets.end(), sortByOrder);

        stream << "\n[dev_" << device.deviceId << "]\n";
        stream << "type=" << device.transport.protocolOptions.value(QStringLiteral("type")).toString(QStringLiteral("TCP")).toUpper() << "\n";
        stream << "yx_type=" << (device.modbus.yxType.trimmed().isEmpty() ? QStringLiteral("BIT") : device.modbus.yxType.trimmed()) << "\n";
        stream << "yc_type=" << (device.modbus.ycType.trimmed().isEmpty() ? QStringLiteral("WORD") : device.modbus.ycType.trimmed()) << "\n";
        stream << "yt_type=" << (device.modbus.ytType.trimmed().isEmpty() ? QStringLiteral("WORD") : device.modbus.ytType.trimmed()) << "\n";
        stream << "yx_poll_num=" << yxPolls.size() << "\n";
        stream << "yc_poll_num=" << ycPolls.size() << "\n";
        stream << "yk_set_num=" << ykSets.size() << "\n";
        stream << "yt_set_num=" << ytSets.size() << "\n";

        if (!device.modbus.ycScale.trimmed().isEmpty()) {
            stream << "yc_scale=" << device.modbus.ycScale.trimmed() << "\n";
        }
        if (!device.modbus.ytScale.trimmed().isEmpty()) {
            stream << "yt_scale=" << device.modbus.ytScale.trimmed() << "\n";
        }

        for (int index = 0; index < yxPolls.size(); ++index) {
            const ModbusPollGroup &group = yxPolls.at(index);
            const int order = index + 1;
            stream << "yx_poll" << order << "=" << modbusIniPollLine(group) << "\n";
            if (!group.dataType.trimmed().isEmpty() && group.dataType != device.modbus.yxType) {
                stream << "yx_type" << order << "=" << group.dataType.trimmed() << "\n";
            }
        }
        for (int index = 0; index < ycPolls.size(); ++index) {
            const ModbusPollGroup &group = ycPolls.at(index);
            const int order = index + 1;
            stream << "yc_poll" << order << "=" << modbusIniPollLine(group) << "\n";
            if (!group.dataType.trimmed().isEmpty() && group.dataType != device.modbus.ycType) {
                stream << "yc_type" << order << "=" << group.dataType.trimmed() << "\n";
            }
            if (!group.scale.trimmed().isEmpty() && group.scale != device.modbus.ycScale) {
                stream << "yc_scale" << order << "=" << group.scale.trimmed() << "\n";
            }
        }
        for (int index = 0; index < ykSets.size(); ++index) {
            stream << "yk_set" << (index + 1) << "=" << modbusIniSetLine(ykSets.at(index)) << "\n";
        }
        for (int index = 0; index < ytSets.size(); ++index) {
            const ModbusSetPoint &setPoint = ytSets.at(index);
            const int order = index + 1;
            stream << "yt_set" << order << "=" << modbusIniSetLine(setPoint) << "\n";
            if (!setPoint.dataType.trimmed().isEmpty() && setPoint.dataType != device.modbus.ytType) {
                stream << "yt_type" << order << "=" << setPoint.dataType.trimmed() << "\n";
            }
            if (!setPoint.scale.trimmed().isEmpty() && setPoint.scale != device.modbus.ytScale) {
                stream << "yt_scale" << order << "=" << setPoint.scale.trimmed() << "\n";
            }
        }

        QSet<QString> structuredKeys = {
            QStringLiteral("type"),
            QStringLiteral("yx_type"),
            QStringLiteral("yc_type"),
            QStringLiteral("yt_type"),
            QStringLiteral("yx_poll_num"),
            QStringLiteral("yc_poll_num"),
            QStringLiteral("yk_set_num"),
            QStringLiteral("yt_set_num"),
            QStringLiteral("yc_scale"),
            QStringLiteral("yt_scale")
        };
        for (int index = 1; index <= yxPolls.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yx_poll%1").arg(index));
            structuredKeys.insert(QStringLiteral("yx_type%1").arg(index));
        }
        for (int index = 1; index <= ycPolls.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yc_poll%1").arg(index));
            structuredKeys.insert(QStringLiteral("yc_type%1").arg(index));
            structuredKeys.insert(QStringLiteral("yc_scale%1").arg(index));
        }
        for (int index = 1; index <= ykSets.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yk_set%1").arg(index));
        }
        for (int index = 1; index <= ytSets.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yt_set%1").arg(index));
            structuredKeys.insert(QStringLiteral("yt_type%1").arg(index));
            structuredKeys.insert(QStringLiteral("yt_scale%1").arg(index));
        }

        for (const QString &key : device.modbus.rawExtra.keys()) {
            if (structuredKeys.contains(key)) {
                continue;
            }
            stream << key << "=" << device.modbus.rawExtra.value(key).toString() << "\n";
        }
    }

    return content;
}

QString buildDlt645IniContent(const ConfigProject &project,
                              const QList<ProtocolDeviceInstance> &devices)
{
    QString content;
    QTextStream stream(&content);

    stream << "[485_para]\n";
    stream << "serialPort=" << (project.dlt645.serialPort.trimmed().isEmpty()
        ? QStringLiteral("/dev/ttyS1")
        : project.dlt645.serialPort.trimmed()) << "\n";
    stream << "baud=" << (project.dlt645.baud.trimmed().isEmpty()
        ? QStringLiteral("9600")
        : project.dlt645.baud.trimmed()) << "\n";
    stream << "dataBits=" << (project.dlt645.dataBits.trimmed().isEmpty()
        ? QStringLiteral("8")
        : project.dlt645.dataBits.trimmed()) << "\n";
    stream << "stopBits=" << (project.dlt645.stopBits.trimmed().isEmpty()
        ? QStringLiteral("1")
        : project.dlt645.stopBits.trimmed()) << "\n";
    stream << "parity=" << (project.dlt645.parity.trimmed().isEmpty()
        ? QStringLiteral("even")
        : project.dlt645.parity.trimmed()) << "\n";
    stream << "frameInterval=" << (project.dlt645.frameInterval.trimmed().isEmpty()
        ? QStringLiteral("100")
        : project.dlt645.frameInterval.trimmed()) << "\n";
    if (!project.dlt645.hwVariant.trimmed().isEmpty()) {
        stream << "hw_variant=" << project.dlt645.hwVariant.trimmed() << "\n";
    }
    for (const QString &key : project.dlt645.rawExtra.keys()) {
        stream << key << "=" << project.dlt645.rawExtra.value(key).toString() << "\n";
    }

    for (const ProtocolDeviceInstance &device : devices) {
        QList<Dlt645PollGroup> yxPolls;
        QList<Dlt645PollGroup> ycPolls;
        QList<Dlt645SetPoint> ykSets;
        QList<Dlt645SetPoint> ytSets;

        for (const Dlt645PollGroup &group : device.dlt645.pollGroups) {
            if (group.kind == Dlt645PointKind::Yx) {
                yxPolls.append(group);
            } else {
                ycPolls.append(group);
            }
        }
        for (const Dlt645SetPoint &setPoint : device.dlt645.setPoints) {
            if (setPoint.kind == Dlt645PointKind::Yk) {
                ykSets.append(setPoint);
            } else {
                ytSets.append(setPoint);
            }
        }

        auto sortByOrder = [](const auto &left, const auto &right) {
            if (left.order != right.order) {
                return left.order < right.order;
            }
            if (left.groupNo != right.groupNo) {
                return left.groupNo < right.groupNo;
            }
            if constexpr (std::is_same_v<std::decay_t<decltype(left)>, Dlt645SetPoint>) {
                return left.entryNo < right.entryNo;
            } else {
                return left.pollDi < right.pollDi;
            }
        };
        std::sort(yxPolls.begin(), yxPolls.end(), sortByOrder);
        std::sort(ycPolls.begin(), ycPolls.end(), sortByOrder);
        std::sort(ykSets.begin(), ykSets.end(), sortByOrder);
        std::sort(ytSets.begin(), ytSets.end(), sortByOrder);

        stream << "\n[dev_" << device.deviceId << "]\n";
        stream << "userID=" << (device.dlt645.userId.trimmed().isEmpty() ? QStringLiteral("0") : device.dlt645.userId.trimmed()) << "\n";
        stream << "password=" << (device.dlt645.password.trimmed().isEmpty() ? QStringLiteral("0") : device.dlt645.password.trimmed()) << "\n";
        stream << "yx_type=" << (device.dlt645.yxType.trimmed().isEmpty() ? QStringLiteral("BIN") : device.dlt645.yxType.trimmed()) << "\n";
        stream << "yc_type=" << (device.dlt645.ycType.trimmed().isEmpty() ? QStringLiteral("BCD") : device.dlt645.ycType.trimmed()) << "\n";
        stream << "yt_type=" << (device.dlt645.ytType.trimmed().isEmpty() ? QStringLiteral("BCD") : device.dlt645.ytType.trimmed()) << "\n";
        stream << "yx_poll_num=" << yxPolls.size() << "\n";
        stream << "yc_poll_num=" << ycPolls.size() << "\n";
        stream << "yk_set_num=" << ykSets.size() << "\n";
        stream << "yt_set_num=" << ytSets.size() << "\n";

        for (int index = 0; index < yxPolls.size(); ++index) {
            const Dlt645PollGroup &group = yxPolls.at(index);
            const int order = index + 1;
            stream << "yx_poll" << order << "=" << dlt645IniPollLine(group) << "\n";
            if (!group.dataType.trimmed().isEmpty() && group.dataType != device.dlt645.yxType) {
                stream << "yx_type" << order << "=" << group.dataType.trimmed() << "\n";
            }
        }
        for (int index = 0; index < ycPolls.size(); ++index) {
            const Dlt645PollGroup &group = ycPolls.at(index);
            const int order = index + 1;
            stream << "yc_poll" << order << "=" << dlt645IniPollLine(group) << "\n";
            if (!group.dataType.trimmed().isEmpty() && group.dataType != device.dlt645.ycType) {
                stream << "yc_type" << order << "=" << group.dataType.trimmed() << "\n";
            }
        }
        for (int index = 0; index < ykSets.size(); ++index) {
            stream << "yk_set" << (index + 1) << "=" << dlt645IniSetLine(ykSets.at(index)) << "\n";
        }
        for (int index = 0; index < ytSets.size(); ++index) {
            const Dlt645SetPoint &setPoint = ytSets.at(index);
            const int order = index + 1;
            stream << "yt_set" << order << "=" << dlt645IniSetLine(setPoint) << "\n";
            if (!setPoint.dataType.trimmed().isEmpty() && setPoint.dataType != device.dlt645.ytType) {
                stream << "yt_type" << order << "=" << setPoint.dataType.trimmed() << "\n";
            }
        }

        QSet<QString> structuredKeys = {
            QStringLiteral("userID"),
            QStringLiteral("password"),
            QStringLiteral("yx_type"),
            QStringLiteral("yc_type"),
            QStringLiteral("yt_type"),
            QStringLiteral("yx_poll_num"),
            QStringLiteral("yc_poll_num"),
            QStringLiteral("yk_set_num"),
            QStringLiteral("yt_set_num")
        };
        for (int index = 1; index <= yxPolls.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yx_poll%1").arg(index));
            structuredKeys.insert(QStringLiteral("yx_type%1").arg(index));
        }
        for (int index = 1; index <= ycPolls.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yc_poll%1").arg(index));
            structuredKeys.insert(QStringLiteral("yc_type%1").arg(index));
        }
        for (int index = 1; index <= ykSets.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yk_set%1").arg(index));
        }
        for (int index = 1; index <= ytSets.size(); ++index) {
            structuredKeys.insert(QStringLiteral("yt_set%1").arg(index));
            structuredKeys.insert(QStringLiteral("yt_type%1").arg(index));
        }

        for (const QString &key : device.dlt645.rawExtra.keys()) {
            if (structuredKeys.contains(key)) {
                continue;
            }
            stream << key << "=" << device.dlt645.rawExtra.value(key).toString() << "\n";
        }
    }

    return content;
}

const ModelTemplate *findModelById(const ConfigProject &project,
                                   const QString &modelId)
{
    for (const ModelTemplate &model : project.models) {
        if (model.modelId == modelId) {
            return &model;
        }
    }

    return nullptr;
}

QSet<QString> duplicateDataRefsForModel(const ModelTemplate &model)
{
    QSet<QString> seenRefs;
    QSet<QString> duplicateRefs;

    for (const ServiceTemplate &service : model.services) {
        for (const PointTemplate &point : service.points) {
            const QString ref = point.dataRef().trimmed();
            if (ref.isEmpty()) {
                continue;
            }

            if (seenRefs.contains(ref)) {
                duplicateRefs.insert(ref);
            } else {
                seenRefs.insert(ref);
            }
        }
    }

    return duplicateRefs;
}

QSet<QString> duplicateBindingAddresses(const ProtocolDeviceInstance &device)
{
    QSet<QString> seenAddresses;
    QSet<QString> duplicateAddresses;

    for (const PointBinding &binding : device.bindings) {
        if (!binding.enabled || isVirtualPointBinding(binding)) {
            continue;
        }

        const QString address = binding.address.trimmed();
        if (address.isEmpty()) {
            continue;
        }

        if (seenAddresses.contains(address)) {
            duplicateAddresses.insert(address);
        } else {
            seenAddresses.insert(address);
        }
    }

    return duplicateAddresses;
}

QString iec104ChannelKey(const ProtocolDeviceInstance &device)
{
    return QStringLiteral("%1|%2|%3")
        .arg(device.transport.ip.trimmed().toLower(),
             device.transport.port.trimmed(),
             device.transport.stationAddress.trimmed());
}

QString iec104ChannelDisplayName(const ProtocolDeviceInstance &device)
{
    return QStringLiteral("IP=%1，端口=%2，104公共地址=%3")
        .arg(device.transport.ip.trimmed(),
             device.transport.port.trimmed(),
             device.transport.stationAddress.trimmed());
}

QHash<QString, QSet<QString>> duplicateIec104BindingAddressesByChannel(const QList<ProtocolDeviceInstance> &devices)
{
    QHash<QString, QSet<QString>> seenAddressesByChannel;
    QHash<QString, QSet<QString>> duplicateAddressesByChannel;

    for (const ProtocolDeviceInstance &device : devices) {
        if (device.protocol != ProtocolType::Iec104) {
            continue;
        }

        const QString channelKey = iec104ChannelKey(device);
        QSet<QString> &seenAddresses = seenAddressesByChannel[channelKey];
        QSet<QString> &duplicateAddresses = duplicateAddressesByChannel[channelKey];

        for (const PointBinding &binding : device.bindings) {
            if (!binding.enabled || isVirtualPointBinding(binding)) {
                continue;
            }

            const QString address = binding.address.trimmed();
            if (address.isEmpty()) {
                continue;
            }

            if (seenAddresses.contains(address)) {
                duplicateAddresses.insert(address);
            } else {
                seenAddresses.insert(address);
            }
        }
    }

    return duplicateAddressesByChannel;
}

QString normalizedModbusRtuPortName(const QString &port)
{
    QString normalized = port.trimmed().toUpper();
    if (normalized.startsWith(QStringLiteral("RS485"))) {
        normalized.remove(QChar('_'));
    }
    return normalized;
}

QString modbusPhysicalChannelKey(const ProtocolDeviceInstance &device)
{
    const QString type = device.transport.protocolOptions
                             .value(QStringLiteral("type"))
                             .toString(QStringLiteral("TCP"))
                             .trimmed()
                             .toUpper();
    if (type == QStringLiteral("RTU")) {
        const QJsonObject serial = device.transport.serial;
        return QStringLiteral("%1|%2|%3|%4|%5|%6|%7")
            .arg(QStringLiteral("RTU"),
                 normalizedModbusRtuPortName(jsonValueToString(serial.value(QStringLiteral("serialPort")))),
                 jsonValueToString(serial.value(QStringLiteral("baud"))).trimmed(),
                 jsonValueToString(serial.value(QStringLiteral("parity"))).trimmed().toUpper(),
                 jsonValueToString(serial.value(QStringLiteral("dataBits"))).trimmed(),
                 jsonValueToString(serial.value(QStringLiteral("stopBits"))).trimmed(),
                 device.transport.stationAddress.trimmed());
    }

    return QStringLiteral("%1|%2|%3|%4")
        .arg(QStringLiteral("TCP"),
             device.transport.ip.trimmed().toLower(),
             device.transport.port.trimmed(),
             device.transport.stationAddress.trimmed());
}

QString modbusPhysicalChannelDisplayName(const ProtocolDeviceInstance &device)
{
    const QString type = device.transport.protocolOptions
                             .value(QStringLiteral("type"))
                             .toString(QStringLiteral("TCP"))
                             .trimmed()
                             .toUpper();
    if (type == QStringLiteral("RTU")) {
        const QJsonObject serial = device.transport.serial;
        return QStringLiteral("RTU串口=%1，波特率=%2，校验=%3，数据位=%4，停止位=%5，协议地址=%6")
            .arg(jsonValueToString(serial.value(QStringLiteral("serialPort"))).trimmed(),
                 jsonValueToString(serial.value(QStringLiteral("baud"))).trimmed(),
                 jsonValueToString(serial.value(QStringLiteral("parity"))).trimmed().toUpper(),
                 jsonValueToString(serial.value(QStringLiteral("dataBits"))).trimmed(),
                 jsonValueToString(serial.value(QStringLiteral("stopBits"))).trimmed(),
                 device.transport.stationAddress.trimmed());
    }

    return QStringLiteral("IP=%1，端口=%2，协议地址=%3")
        .arg(device.transport.ip.trimmed(),
             device.transport.port.trimmed(),
             device.transport.stationAddress.trimmed());
}

QString modbusAddressSpaceKey(int funCode)
{
    if (funCode == 1 || funCode == 5 || funCode == 15) {
        return QStringLiteral("coil");
    }
    if (funCode == 2) {
        return QStringLiteral("discrete");
    }
    if (funCode == 3 || funCode == 6 || funCode == 16) {
        return QStringLiteral("holding");
    }
    if (funCode == 4) {
        return QStringLiteral("input");
    }
    return QStringLiteral("func%1").arg(funCode);
}

QHash<QString, QSet<QString>> duplicateModbusRegisterAddressesByPhysicalChannel(const QList<ProtocolDeviceInstance> &devices)
{
    struct RegisterRange
    {
        QString startAddress;
        QString addressSpace;
        int start = 0;
        int end = 0;
        bool pocketBit = false;
        int sourceIndex = -1;
        int bitIndex = -1;
    };

    QHash<QString, QList<RegisterRange>> seenRangesByChannel;
    QHash<QString, QSet<QString>> duplicateAddressesByChannel;

    for (const ProtocolDeviceInstance &device : devices) {
        if (device.protocol != ProtocolType::Modbus
            && device.appType.compare(QStringLiteral("South_Modbus"), Qt::CaseInsensitive) != 0
            && device.appType.compare(QStringLiteral("cepmodbus"), Qt::CaseInsensitive) != 0) {
            continue;
        }

        const QString channelKey = modbusPhysicalChannelKey(device);
        QList<RegisterRange> &seenRanges = seenRangesByChannel[channelKey];
        QSet<QString> &duplicateAddresses = duplicateAddressesByChannel[channelKey];

        for (const PointBinding &binding : device.bindings) {
            if (!binding.enabled
                || isVirtualPointBinding(binding)
                || !binding.extensions.contains(QStringLiteral("modbusRegisterAddress"))) {
                continue;
            }

            const QJsonValue value = binding.extensions.value(QStringLiteral("modbusRegisterAddress"));
            bool ok = value.isDouble();
            const int registerAddress = value.isDouble()
                ? value.toInt()
                : value.toString().trimmed().toInt(&ok, 0);
            if (!ok) {
                continue;
            }

            const QString kind = modbusBindingKind(binding);
            const int defaultFunCode = kind == QStringLiteral("yx")
                ? 2
                : (kind == QStringLiteral("yc") ? 3 : 6);
            const int funCode = modbusBindingInt(binding, QStringLiteral("modbusFunctionCode"), defaultFunCode);
            const QString dataType = modbusBindingString(binding,
                                                         QStringLiteral("modbusDataType"),
                                                         kind == QStringLiteral("yx") ? QStringLiteral("BIT") : QStringLiteral("WORD"));
            const int registerCount = (funCode == 1 || funCode == 2 || funCode == 5 || funCode == 15)
                ? 1
                : qMax(1, modbusTypeRegisterCount(dataType));

            RegisterRange current;
            current.startAddress = QString::number(registerAddress);
            current.addressSpace = modbusAddressSpaceKey(funCode);
            current.start = registerAddress;
            current.end = registerAddress + registerCount;
            current.pocketBit = dataType.compare(QStringLiteral("POCKETBIT"), Qt::CaseInsensitive) == 0;
            current.sourceIndex = modbusBindingInt(binding, QStringLiteral("modbusSourceIndex"), -1);
            current.bitIndex = modbusBindingInt(binding, QStringLiteral("modbusBitIndex"), -1);

            for (const RegisterRange &seen : seenRanges) {
                if (seen.addressSpace != current.addressSpace) {
                    continue;
                }
                const bool distinctPocketBits = current.pocketBit && seen.pocketBit
                    && current.start == seen.start
                    && current.sourceIndex >= 0 && current.bitIndex >= 0
                    && (current.sourceIndex != seen.sourceIndex || current.bitIndex != seen.bitIndex);
                if (!distinctPocketBits && current.start < seen.end && seen.start < current.end) {
                    duplicateAddresses.insert(seen.startAddress);
                    duplicateAddresses.insert(current.startAddress);
                }
            }
            seenRanges.append(current);
        }
    }

    return duplicateAddressesByChannel;
}

ImportIssueSeverity importSeverityForConfigIssue(ConfigIssueSeverity severity)
{
    switch (severity) {
    case ConfigIssueSeverity::Info:
        return ImportIssueSeverity::Info;
    case ConfigIssueSeverity::Warning:
        return ImportIssueSeverity::Warning;
    case ConfigIssueSeverity::Error:
        return ImportIssueSeverity::Error;
    }

    return ImportIssueSeverity::Error;
}

QString formatConfigIssue(const ConfigIssue &issue)
{
    QString severity;
    switch (issue.severity) {
    case ConfigIssueSeverity::Info:
        severity = QStringLiteral("提示");
        break;
    case ConfigIssueSeverity::Warning:
        severity = QStringLiteral("警告");
        break;
    case ConfigIssueSeverity::Error:
        severity = QStringLiteral("错误");
        break;
    }

    QStringList parts;
    parts << severity;
    if (!issue.module.trimmed().isEmpty()) {
        parts << issue.module.trimmed();
    }
    if (!issue.objectId.trimmed().isEmpty()) {
        parts << issue.objectId.trimmed();
    }
    parts << issue.message;
    return QStringLiteral("[%1] %2").arg(parts.takeFirst(), parts.join(QStringLiteral(" / ")));
}

void appendConfigIssuesToReport(const QList<ConfigIssue> &issues,
                                const QString &filePath,
                                ImportReport &report)
{
    for (const ConfigIssue &issue : issues) {
        report.addIssue(importSeverityForConfigIssue(issue.severity),
                        filePath,
                        formatConfigIssue(issue));
    }
}

void appendConfigIssuesToReport(const QList<ConfigIssue> &issues,
                                const QString &filePath,
                                ExportReport &report)
{
    for (const ConfigIssue &issue : issues) {
        report.addIssue(importSeverityForConfigIssue(issue.severity),
                        filePath,
                        formatConfigIssue(issue));
    }
}

} // namespace detail

using namespace detail;

bool ImportReport::hasErrors() const
{
    for (const ImportIssue &issue : issues) {
        if (issue.severity == ImportIssueSeverity::Error) {
            return true;
        }
    }

    return false;
}

void ImportReport::addIssue(ImportIssueSeverity severity,
                            const QString &filePath,
                            const QString &message)
{
    ImportIssue issue;
    issue.severity = severity;
    issue.filePath = filePath;
    issue.message = message;
    issues.append(issue);
}

bool ExportReport::hasErrors() const
{
    for (const ImportIssue &issue : issues) {
        if (issue.severity == ImportIssueSeverity::Error) {
            return true;
        }
    }

    return false;
}

void ExportReport::addIssue(ImportIssueSeverity severity,
                            const QString &filePath,
                            const QString &message)
{
    ImportIssue issue;
    issue.severity = severity;
    issue.filePath = filePath;
    issue.message = message;
    issues.append(issue);
}

ConfigProjectManager::ConfigProjectManager() = default;

void ConfigProjectManager::createEmptyProject(const QString &projectName,
                                             const QString &sourceRoot)
{
    m_project = ConfigProject();
    m_project.projectId = QUuid::createUuid().toString(QUuid::WithoutBraces);
    m_project.projectName = projectName;
    m_project.sourceRoot = sourceRoot;
    m_project.northApp = QStringLiteral("North_CEP");
    m_project.logicApp = QStringLiteral("LogicCenter");
}

bool ConfigProjectManager::importIec104AppDirectory(const QString &appDir,
                                                    ImportReport &report)
{
    if (m_project.projectId.isEmpty()) {
        createEmptyProject(QStringLiteral("导入工程"), appDir);
    }

    return m_iec104Importer.importAppDirectory(appDir, m_project, report);
}

bool ConfigProjectManager::importModbusAppDirectory(const QString &appDir,
                                                    ImportReport &report)
{
    if (m_project.projectId.isEmpty()) {
        createEmptyProject(QStringLiteral("导入工程"), appDir);
    }

    return m_modbusImporter.importAppDirectory(appDir, m_project, report);
}

bool ConfigProjectManager::importDlt645AppDirectory(const QString &appDir,
                                                    ImportReport &report)
{
    if (m_project.projectId.isEmpty()) {
        createEmptyProject(QStringLiteral("导入工程"), appDir);
    }

    return m_dlt645Importer.importAppDirectory(appDir, m_project, report);
}

bool ConfigProjectManager::importLogicCenterConfigFile(const QString &filePath,
                                                       ImportReport &report)
{
    if (m_project.projectId.isEmpty()) {
        createEmptyProject(QStringLiteral("导入工程"), QFileInfo(filePath).absolutePath());
    }

    QJsonDocument document;
    QString errorMessage;
    if (!loadJsonDocument(filePath, document, errorMessage)) {
        report.addIssue(ImportIssueSeverity::Error, filePath, errorMessage);
        return false;
    }

    m_project.logicCenter = parseLogicCenterConfig(document.object());
    m_project.logic = document.object();
    appendConfigIssuesToReport(validateLogicCenterConfig(m_project.logicCenter, &m_project),
                               filePath,
                               report);
    return true;
}

ConfigProject &ConfigProjectManager::project()
{
    return m_project;
}

const ConfigProject &ConfigProjectManager::project() const
{
    return m_project;
}

} // namespace configtool

